"""users judges

Revision ID: 4732b09c085b
Revises: 95105c7bf9ed
Create Date: 2021-04-24 20:32:18.717918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4732b09c085b'
down_revision = '95105c7bf9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('judge', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'judge')
    # ### end Alembic commands ###
